# Generated by Django 4.1.4 on 2022-12-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_breed',
            field=models.ManyToManyField(blank=True, to='home.animalbreed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_color',
            field=models.ManyToManyField(blank=True, to='home.animalcolor'),
        ),
    ]
